// ================ Start backend tasks team data ================
// ទិន្នន័យតារាង BACKEND TASKS TEAM (ដូច Notion board ក្នុង sample)
// ប្រើក្នុង: pages/admin/BackendTasksTeam.jsx

export const BACKEND_TASK_COLUMNS = [
  { id: 'name', label: 'Name', width: 'min-w-[200px]' },
  { id: 'status', label: 'Status', width: 'w-[120px]' },
  { id: 'tags', label: 'Tags', width: 'w-[110px]' },
  { id: 'member', label: 'Member', width: 'w-[100px]' },
  { id: 'day', label: 'Day', width: 'min-w-[140px]' },
  { id: 'priority', label: 'Priority', width: 'w-[100px]' },
  { id: 'description', label: 'Description', width: 'min-w-[280px]' },
]

export const BACKEND_TASK_ROWS = [
  {
    id: '1',
    name: 'step implement database',
    status: 'Done',
    tags: 'Database',
    member: 'team',
    day: '23 April - Present',
    priority: 'Critical',
    description: 'entity relational database definition',
  },
  {
    id: '2',
    name: 'project Overview',
    status: 'Done',
    tags: 'project',
    member: 'nang',
    day: 'All',
    priority: 'Critical',
    description:
      'fullstack backend project: express.js + MySQL + Sequelize. 6 members, 12 days. KHALIK enforced.',
  },
  {
    id: '3',
    name: 'goal',
    status: 'Done',
    tags: 'project',
    member: 'nang',
    day: 'All',
    priority: 'Critical',
    description:
      'build complete backend API with authentication, mentor system, community, subscription, billing, admin dashboard',
  },
  {
    id: '4',
    name: 'tech stack',
    status: 'Done',
    tags: 'project',
    member: 'nang',
    day: '25th May',
    priority: 'Critical',
    description: 'express.js, node.js, mysql, sequelize, redis, JWT, docker, nginx',
  },
  {
    id: '5',
    name: 'Architecture',
    status: 'Done',
    tags: 'Project',
    member: 'nang',
    day: '25th May',
    priority: 'Critical',
    description: 'Repository Pattern -> Service Layer -> Controller -> Route. No spaghetti code.',
  },
  {
    id: '6',
    name: 'Database Schema Design',
    status: 'Done',
    tags: 'Database',
    member: 'Rothanak',
    day: '25th May',
    priority: 'Critical',
    description: 'Complete ERD with all 16 tables. PK/FK defined. Presented to team.',
  },
  {
    id: '7',
    name: 'Sequelize Models',
    status: 'Done',
    tags: 'Database',
    member: 'Rothanak',
    day: '25th May',
    priority: 'Critical',
    description:
      'All models with KHAL (foreign key references, onUpdate: CASCADE, onDelete: RESTRICT/SET NULL).',
  },
  {
    id: '8',
    name: 'Seeders',
    status: 'Done',
    tags: 'Database',
    member: 'Rothanak',
    day: '26th May',
    priority: 'Critical',
    description:
      'Master data: 8 provinces, 3 user types, 5 skills, 7 sub-skills, 3 subscription plans.',
  },
  {
    id: '9',
    name: 'Triggers',
    status: 'Done',
    tags: 'Database',
    member: 'Rothanak',
    day: '27th May',
    priority: 'Critical',
    description:
      '6 triggers: auto-update_date, audit logs, data validation, expiry check, community history.',
  },
  {
    id: '10',
    name: 'Views',
    status: 'Done',
    tags: 'Database',
    member: 'Rothanak',
    day: '27th May',
    priority: 'Critical',
    description:
      '4 views: mentor full profile, user full profile, community post detail, billing summary, active mentors.',
  },
  {
    id: '11',
    name: 'FK Relationships',
    status: 'Done',
    tags: 'Database',
    member: 'Rothanak',
    day: '25th May',
    priority: 'Critical',
    description:
      'UserType->Users, User->Student/Mentor/Admin, Mentor->Portfolio/Post, Skill->SubSkill, MentorSkill, CommunityType->Post, User->Post, Post->History, Plan->Subscription, User->Subscription, User->AccountHistory',
  },
  {
    id: '12',
    name: 'Auth System',
    status: 'In Progress',
    tags: 'Auth',
    member: 'ravy',
    day: '28th May',
    priority: 'High',
    description:
      'Register, login, JWT, logout, refresh, password reset, email verification, admin auth',
  },
  {
    id: '13',
    name: 'JWT middleware',
    status: 'In Progress',
    tags: 'Auth',
    member: 'ravy',
    day: '28th May',
    priority: 'High',
    description: 'verify JWT middleware protecting all private routes, role-based access.',
  },
  {
    id: '14',
    name: 'User profile',
    status: 'In Progress',
    tags: 'Auth',
    member: 'kana',
    day: '28th May',
    priority: 'High',
    description: 'GET/PUT /api/v1/users/me. profile picture upload.',
  },
  {
    id: '15',
    name: 'Rate Limiting',
    status: 'In Progress',
    tags: 'Auth',
    member: 'ravy',
    day: '28th May',
    priority: 'Medium',
    description: 'redis-based rate limiting on auth endpoints.',
  },
  {
    id: '16',
    name: 'request validation',
    status: 'In Progress',
    tags: 'Auth',
    member: 'kana',
    day: '28th May',
    priority: 'High',
    description: 'joi validation for all auth endpoints.',
  },
  {
    id: '17',
    name: 'Student System',
    status: 'In Progress',
    tags: 'Student',
    member: 'Phy',
    day: '29th May',
    priority: 'High',
    description:
      'Student CRUD, dashboard, subscription view, account history, search mentor, community posts.',
  },
  {
    id: '18',
    name: 'Student Dashboard',
    status: 'In Progress',
    tags: 'Student',
    member: 'Phy',
    day: '27th - 28th May',
    priority: 'High',
    description: 'Aggregated data: profile, subscriptions, history, posts.',
  },
  {
    id: '19',
    name: 'Search Mentor',
    status: 'In Progress',
    tags: 'Student',
    member: 'Phy',
    day: '30th May',
    priority: 'High',
    description: 'Student can search and view mentor profiles.',
  },
  {
    id: '20',
    name: 'Mentor System',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: '29th May - 2nd June',
    priority: 'High',
    description: 'Mentor CRUD, portfolio, skills, posts, search, analytics.',
  },
  {
    id: '21',
    name: 'Portfolio',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: '27th May',
    priority: 'High',
    description: 'Mentor portfolio CRUD with file upload.',
  },
  {
    id: '22',
    name: 'Skill Assignment',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: '28th May',
    priority: 'High',
    description: 'link mentor to skills. Many to many via mentor_skill table.',
  },
  {
    id: '23',
    name: 'Advanced Search',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: '30th May',
    priority: 'High',
    description: 'filter by skill_id, province_id, min_price, experience_years.',
  },
  {
    id: '24',
    name: 'Community System',
    status: 'In Progress',
    tags: 'Community',
    member: 'Rothanak',
    day: '28th May - 1st June',
    priority: 'High',
    description:
      'Community post CRUD, file upload, like, comment, trending, history audit.',
  },
  {
    id: '25',
    name: 'File Upload',
    status: 'In Progress',
    tags: 'Community',
    member: 'Rothanak',
    day: '28th May',
    priority: 'High',
    description: 'multer image upload for community posts.',
  },
  {
    id: '26',
    name: 'Like + Comment',
    status: 'In Progress',
    tags: 'Community',
    member: 'Rothanak',
    day: '30th May',
    priority: 'High',
    description: 'user interaction system.',
  },
  {
    id: '27',
    name: 'Trending Posts',
    status: 'In Progress',
    tags: 'Community',
    member: 'Rothanak',
    day: '1st June',
    priority: 'High',
    description: 'Algorithm for trending based on likes, comments, views.',
  },
  {
    id: '28',
    name: 'subscription system',
    status: 'In Progress',
    tags: 'billing',
    member: 'Heing',
    day: '29th May - 1st June',
    priority: 'High',
    description:
      'subscription plans, subscribe, cancel, auto-renewal, status tracking.',
  },
  {
    id: '29',
    name: 'billing + Payment',
    status: 'In Progress',
    tags: 'billing',
    member: 'Heing',
    day: '29th May - 2nd June',
    priority: 'High',
    description:
      'Payment processing, Stripe webhook, transaction logs, billing reports.',
  },
  // --- Mentor System test breakdown (Notion / feature/05) ---
  {
    id: '30',
    name: 'Mentor CRUD',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: 'Test',
    priority: 'High',
    description: 'Full Create, Read, Update, Delete operations for mentor profiles',
  },
  {
    id: '31',
    name: 'Portfolio Management',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: 'Test',
    priority: 'High',
    description: 'Portfolio CRUD — projects, experience, achievements; file upload',
  },
  {
    id: '32',
    name: 'Skills Management',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: 'Test',
    priority: 'High',
    description: 'Add, update, manage skills/expertise with proficiency levels',
  },
  {
    id: '33',
    name: 'Mentor Posts',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: 'Test',
    priority: 'High',
    description: 'CRUD professional or educational posts',
  },
  {
    id: '34',
    name: 'Mentor Search',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: 'Test',
    priority: 'High',
    description: 'Search by skills, experience, rating, availability; filters + pagination',
  },
  {
    id: '35',
    name: 'Analytics',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: 'Test',
    priority: 'High',
    description: 'Profile views, student engagement, earnings, session stats',
  },
  {
    id: '36',
    name: 'Models',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: 'Test',
    priority: 'Critical',
    description: 'Mentor, Portfolio, Skill, MentorPost, MentorAnalytics — Sequelize + associations',
  },
  {
    id: '37',
    name: 'Controllers',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: 'Test',
    priority: 'High',
    description: 'Business logic in dedicated controllers (MVC)',
  },
  {
    id: '38',
    name: 'Routes',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: 'Test',
    priority: 'High',
    description: 'Clean routes under /api/v1/mentors prefix',
  },
  {
    id: '39',
    name: 'Auth & Authorization',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: 'Test',
    priority: 'Critical',
    description: 'JWT middleware; mentor role; owner-only protected endpoints',
  },
  {
    id: '40',
    name: 'File Uploads',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: 'Test',
    priority: 'Medium',
    description: 'Portfolio media/document uploads',
  },
  {
    id: '41',
    name: 'Error Handling & Validation',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: 'Test',
    priority: 'High',
    description: 'Validation + consistent API responses (match Student feature)',
  },
  {
    id: '42',
    name: 'Testing',
    status: 'In Progress',
    tags: 'Mentor',
    member: 'HUN',
    day: 'Test',
    priority: 'High',
    description: 'Test all mentor endpoints (Postman / Swagger)',
  },
]
// ================ End backend tasks team data ================
